### ISSUE TITLE
publishing the docker image locally shows error "No space left on device" for Akka cluster

### ISSUE THREAD

**Issue by felipegutierrez** [felipegutierrez/explore-akka#3]
when publishing the docker image locally using the command `sbt docker:publishLocal` and running using the command `docker run -i felipeogutierrez/explore-akka:1.1 42.1`, the following error happens. We might find the solution at the repo [akka-sample-cluster-kubernetes-scala](https://github.com/akka/akka-sample-cluster-kubernetes-scala).

```
you chose the option 42.1
16:03:20.287 [RTJVMCluster-akka.actor.default-dispatcher-4] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
16:03:20.554 [RTJVMCluster-akka.actor.default-dispatcher-4] INFO akka.remote.artery.aeron.ArteryAeronUdpTransport - Started embedded media driver in directory [/dev/shm/aeron-demiourgos728-RTJVMCluster-127353e4-4691-4ecf-8a65-0bd74ada58e7]
16:03:20.759 [RTJVMCluster-akka.actor.default-dispatcher-4] INFO akka.remote.artery.aeron.ArteryAeronUdpTransport - Remoting started with transport [Artery aeron-udp]; listening on address [akka://RTJVMCluster@localhost:2551] with UID [2554294128597434977]
Warning: space is running low in /dev/shm (shm) threshold=167,772,160 usable=58,716,160
16:03:21.150 [RTJVMCluster-akka.actor.default-dispatcher-13] ERROR akka.remote.RemoteActorRef - swallowing exception during message send
io.aeron.exceptions.RegistrationException: correlationId=4, errorCodeValue=0, UncheckedIOException : java.io.IOException: No space left on device
	at io.aeron.ClientConductor.onError(ClientConductor.java:220)
	at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:115)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
	at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:68)
	at io.aeron.ClientConductor.service(ClientConductor.java:1073)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:1122)
	at io.aeron.ClientConductor.addPublication(ClientConductor.java:431)
	at io.aeron.Aeron.addPublication(Aeron.java:273)
	at akka.remote.artery.aeron.AeronSink$$anon$1.<init>(AeronSink.scala:111)
	at akka.remote.artery.aeron.AeronSink.createLogicAndMaterializedValue(AeronSink.scala:108)
	at akka.stream.stage.GraphStageWithMaterializedValue.createLogicAndMaterializedValue(GraphStage.scala:50)
	at akka.stream.impl.GraphStageIsland.materializeAtomic(PhasedFusingActorMaterializer.scala:699)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:498)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:448)
	at akka.stream.impl.PhasedFusingActorMaterializer.materialize(PhasedFusingActorMaterializer.scala:440)
	at akka.stream.scaladsl.RunnableGraph.run(Flow.scala:741)
	at akka.remote.artery.Association.runOutboundControlStream(Association.scala:765)
	at akka.remote.artery.Association.runOutboundStreams(Association.scala:736)
	at akka.remote.artery.Association.associate(Association.scala:729)
	at akka.remote.artery.AssociationRegistry.association(Association.scala:1118)
	at akka.remote.artery.ArteryTransport.association(ArteryTransport.scala:701)
	at akka.remote.artery.ArteryTransport.send(ArteryTransport.scala:687)
	at akka.remote.RemoteActorRef.$bang(RemoteActorRefProvider.scala:735)
	at akka.actor.ActorRef.tell(ActorRef.scala:128)
	at akka.actor.ActorSelection$.rec$1(ActorSelection.scala:287)
	at akka.actor.ActorSelection$.deliverSelection(ActorSelection.scala:291)
	at akka.actor.ActorSelection.tell(ActorSelection.scala:50)
	at akka.actor.ScalaActorSelection.$bang(ActorSelection.scala:302)
	at akka.actor.ScalaActorSelection.$bang$(ActorSelection.scala:302)
	at akka.actor.ActorSelection$$anon$1.$bang(ActorSelection.scala:218)
	at akka.cluster.SeedNodeProcess.$anonfun$receiveJoinSeedNode$1(SeedNodeProcess.scala:59)
	at akka.cluster.SeedNodeProcess.$anonfun$receiveJoinSeedNode$1$adapted(SeedNodeProcess.scala:58)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
	at akka.cluster.SeedNodeProcess.receiveJoinSeedNode(SeedNodeProcess.scala:58)
	at akka.cluster.FirstSeedNodeProcess$$anonfun$receive$1.applyOrElse(SeedNodeProcess.scala:191)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.cluster.SeedNodeProcess.aroundReceive(SeedNodeProcess.scala:18)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
16:03:23.607 [RTJVMCluster-akka.actor.default-dispatcher-13] ERROR akka.remote.artery.aeron.ArteryAeronUdpTransport - Aeron error: 1 observations from 11/23/2020 16:03:21.124 to 11/23/2020 16:03:21.124 for:
 java.io.UncheckedIOException: java.io.IOException: No space left on device
	at io.aeron.driver.buffer.MappedRawLog.<init>(MappedRawLog.java:125)
	at io.aeron.driver.buffer.FileStoreLogFactory.newInstance(FileStoreLogFactory.java:138)
	at io.aeron.driver.buffer.FileStoreLogFactory.newPublication(FileStoreLogFactory.java:97)
	at io.aeron.driver.DriverConductor.newNetworkPublicationLog(DriverConductor.java:1136)
	at io.aeron.driver.DriverConductor.newNetworkPublication(DriverConductor.java:1105)
	at io.aeron.driver.DriverConductor.onAddNetworkPublication(DriverConductor.java:406)
	at io.aeron.driver.ClientCommandAdapter.addPublication(ClientCommandAdapter.java:291)
	at io.aeron.driver.ClientCommandAdapter.onMessage(ClientCommandAdapter.java:84)
	at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:145)
	at io.aeron.driver.ClientCommandAdapter.receive(ClientCommandAdapter.java:66)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:179)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
	at sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:428)
	at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:493)
	at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:605)
	at io.aeron.driver.buffer.MappedRawLog.allocatePages(MappedRawLog.java:217)
	at io.aeron.driver.buffer.MappedRawLog.<init>(MappedRawLog.java:75)
	... 13 more

16:03:26.154 [RTJVMCluster-akka.actor.default-dispatcher-4] INFO org.github.felipegutierrez.explore.akka.clustering.chat.ChatActor - User Alice enter in the cluster new node: akka://RTJVMCluster@localhost:2551


```

**Comment by felipegutierrez** [comment]
put the first Akka-http hello world to un on to k8s (minikube) based on the blog post https://steveking.site/blog/2017/deploying-scala-sbt-microservices-to-kubernetes/
